"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, CalendarDays, Share2 } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Deadline, DeadlinesService } from "@/services/deadlines-service";

export default function DeadlinesPage() {
  const [deadlines, setDeadlines] = useState<Deadline[] | null>(null);
  const [failed, setFailed] = useState(false);
  async function share() { const url = window.location.href; try { if (navigator.share) await navigator.share({ title: "TaxIn60Sec deadlines", text: "A useful view of upcoming tax and compliance deadlines.", url }); else { await navigator.clipboard.writeText(url); } } catch {} }
  useEffect(() => { DeadlinesService.upcoming().then((r) => setDeadlines(r.deadlines)).catch(() => setFailed(true)); }, []);
  const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: "TaxIn60Sec deadlines", description: "Upcoming tax and compliance deadlines supplied by the TaxIn60Sec deadline service." };
  return <main><Navbar /><section className="page-hero"><div className="container-main max-w-4xl"><p className="eyebrow">Free resource</p><div className="mt-3 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-4xl font-bold text-white sm:text-5xl">Upcoming tax and compliance deadlines</h1><p className="section-copy mt-4 max-w-2xl">A practical place to check the dates currently supplied by TaxIn60Sec. Confirm filing obligations for your own circumstances before acting.</p></div><button onClick={share} className="btn-secondary shrink-0"><Share2 size={16} />Share</button></div><div className="mt-8 card-dark overflow-hidden">{deadlines === null && !failed && <div className="space-y-3 p-5">{[1,2,3].map((x) => <div key={x} className="h-14 animate-pulse rounded-xl bg-white/5" />)}</div>}{failed && <div className="p-6"><p className="font-semibold text-white">Deadlines are temporarily unavailable.</p><p className="mt-1 text-sm text-secondary">Try again shortly, or use the health check to understand what may apply to you.</p><Link href="/health-check" className="btn-primary mt-4">Check my tax situation</Link></div>}{deadlines?.map((item) => <div key={item.type} className="flex items-center justify-between gap-4 border-b border-white/10 p-5 last:border-0"><div className="flex gap-3"><CalendarDays className="shrink-0 text-emerald-400" size={19} /><div><p className="font-semibold text-white">{item.title}</p><p className="mt-1 text-sm text-secondary">{new Date(item.dueDate).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</p></div></div><span className="shrink-0 text-sm font-semibold text-emerald-400">{item.daysRemaining <= 0 ? "Due today" : `${item.daysRemaining} days`}</span></div>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-3">{[["Income tax", "/services/itr-filing", "Understand your filing next step"],["GST", "/services/gst-registration", "Organise GST questions"],["Estimate tax", "/tools", "Use the income tax calculator"]].map(([title, href, copy]) => <Link key={title} href={href} className="card-dark p-5 transition hover:border-emerald-400/30"><p className="font-bold text-white">{title}</p><p className="mt-2 text-sm text-secondary">{copy}</p><p className="mt-3 text-sm font-semibold text-emerald-400">Explore <ArrowRight className="inline" size={14} /></p></Link>)}</div></div></section><Footer /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /></main>;
}
