spring.application.name=backend
spring.datasource.url=jdbc:postgresql://ep-calm-lake-aqd0lbv1-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_Vch9pRl3vmZY

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=${PORT:8080}